volumes:
  pg_data:
  static:
  media:

networks:
  foodgram_net:

services:
  frontend:
    container_name: foodgram-front
    build: ./frontend
    volumes:
      - ./frontend/:/app/result_build/
    networks:
      - foodgram_net

  db:
    image: postgres:15
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - foodgram_net

  backend:
    build: ./backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/static/admin/
      - media:/app/media
    ports:
      - "8000:8000"
    networks:
      - foodgram_net

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - media:/app/media
      - static:/app/static
    networks:
      - foodgram_net
    depends_on:
     - frontend
     - backend
