# Generated by Django 5.2.1 on 2025-05-23 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_shoppingcart_options_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_code', models.CharField(max_length=10, unique=True)),
                ('recipe_to_link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Сокращенная ссылка',
            },
        ),
    ]
