# Generated by Django 5.2.1 on 2025-05-29 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Количество (вес, и т.д.) данного ')], verbose_name='Количество (вес, и т.д.)'),
        ),
    ]
