# Generated by Django 5.2.1 on 2025-05-23 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_from', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, который подписался')),
                ('sub_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_to', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, на кого подписались')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['sub_to'],
            },
        ),
    ]
