# Generated by Django 5.2.1 on 2025-05-29 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_sub'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sub',
            options={'ordering': ('sub_to',), 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Уникальный юзернейм может содержать только ', regex='^[\\w.@+-]+\\Z')], verbose_name='Уникальный юзернейм'),
        ),
        migrations.AddConstraint(
            model_name='sub',
            constraint=models.UniqueConstraint(fields=('sub_from', 'sub_to'), name='unique_subscription'),
        ),
        migrations.AddConstraint(
            model_name='sub',
            constraint=models.CheckConstraint(condition=models.Q(('sub_from', models.F('sub_to')), _negated=True), name='prevent_self_subscription'),
        ),
    ]
